import org.gradle.api.publish.maven.MavenPublication

plugins {
    id 'java'
    id 'maven-publish'
}

group 'NyaaCat'

String majorVersion = 1
String minorVersion = 2
String minecraftVersion = "1.21.11"

String buildNumber = System.getenv("BUILD_NUMBER") == null ? "SNAPSHOT" : System.getenv("BUILD_NUMBER")

version = "$majorVersion.$minorVersion-$buildNumber"

boolean releasing = false

String mavenDirectory = System.getenv("MAVEN_DIR") == null ? "$projectDir/repo" : System.getenv("MAVEN_DIR")
String mavenVersion = releasing ? version : "$majorVersion.$minorVersion-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        name 'Paper'
        url 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name 'NyaaCat'
        url 'https://ci.nyaacat.com/maven/'
    }
    maven {
        name 'enginehub'
        url "https://maven.enginehub.org/repo/"
    }
    maven {
        name 'ProtocolLib'
        url "https://repo.dmulloy2.net/nexus/repository/public/"
    }
    maven { name 'aikar'; url 'https://repo.aikar.co/content/groups/aikar/' }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    implementation('cat.nyaa:nyaacore:9.10')
    compileOnly "io.papermc.paper:paper-api:$minecraftVersion-R0.1-SNAPSHOT"
    compileOnly "com.udojava:EvalEx:2.7"

    compileOnly 'com.meowj:LangUtils:2.3-SNAPSHOT'
    compileOnly('com.sk89q.worldguard:worldguard-bukkit:7.0.8-SNAPSHOT') {
        exclude group: 'io.papermc', module: 'paperlib'
        exclude group: 'org.bstats', module: 'bstats-bukkit'
        exclude group: 'org.bukkit', module: 'bukkit'
    }
    implementation 'co.aikar:taskchain-bukkit:3.7.2'
}

task apiJar(type: Jar) {
    includeEmptyDirs = false
    from sourceSets.main.output.classesDirs
    include('**/cat/nyaa/infiniteinfernal/')
}

task sourcesJar(type: Jar) {
    archiveClassifier.set('sources')
    from sourceSets.main.java.srcDirs
}

publishing {
    publications {
        mavenRelease(MavenPublication) {
            from components.java
            afterEvaluate {
                artifacts = [jar, sourcesJar]
            }
            groupId "cat.nyaa"
            artifactId "infiniteinfernal"
            version "$mavenVersion"
        }
    }

    repositories {
        maven {
            url "$mavenDirectory"
        }
    }
}
