language: en_US
nameTag: '[INFERNAL] {level.prefix} {mob.type} Level {level.level}'
bossbar:
  __class__: cat.nyaa.infiniteinfernal.configs.BossbarConfig
  enabled: true
  killsuffix: '[KILLED]'
randomLootChest:
  __class__: cat.nyaa.infiniteinfernal.configs.RandomLootChestConfig
  enabled: true
  items:
    min: 1
    max: 4
  reset:
    minHours: 1
    maxHours: 4
  scan:
    intervalTicks: 200
    chunksPerRun: 2
    maxContainersPerChunk: 32
tags: []
addEffects:
  target_lost: effect:BLINDNESS:10
  disorder: effect:CONFUSION:10
  dementia: effect:SLOW_DIGGING:10
  broken_armor: OOZING
bossSpawnBlockTag: inf-boss
bossSpawnBlockRange: 128
worlds: {}
