name: InfiniteInfernal
main: cat.nyaa.infiniteinfernal.InfPlugin
description: "InfiniteInfernal"
version: 1.2
depend: [NyaaCore,LangUtils]
softdepend: [WorldGuard,NyaaUtils]
authors: [ReinWD]
website: "https://github.com/NyaaCat/InfiniteInfernal"
database: false
api-version: 1.15

commands:
  infiniteinfernal:
    description: "main command for infinite infernal plugin."
    aliases: [ii,im,inf]
    permission: "im.command"
    permission-message: "You don't have required permission <permission>"
  ig:
    description: "main command for infinite infernal plugin."
    permission: "im.group"
    permission-message: "You don't have required permission <permission>"
  imi:
    description: "controls message for infinite infernal plugin"
    permission: "imi.command"
    permission-message: "You don't have required permission <permission>"
  imb:
    description: "controls message for infinite infernal plugin"
    permission: "imb.command"
    permission-message: "You don't have required permission <permission>"
  infdebug:
    description: "debug command for infinite infernal plugin"
    aliases: imd
    permission: "im.debug"
    permission-message: "You don't have required permission <permission>"


permissions:
  im.command:
    description: "main permissions for infinite infernal plugin."
    default: true
  imi.command:
    description: "controls message for infinite infernal plugin"
    default: true
  im.reload:
    description: "reload command for infinite infernal plugin"
    default: op
  im.debug:
    description: "debug command for infinite infernal plugin"
    default: op
  im.spawn:
    description: "permission for \"im.spawn\""
    default: op
  im.addloot:
    description: "permission for \"im.addloot\""
    default: op
  im.getloot:
    description: "permission for \"im.getloot\""
    default: op
  im.setdrop:
    description: "permission for \"im.setdrop\""
    default: op
  im.inspect:
    description: "permission for \"im.inspect\""
    default: op
  im.kill.all:
    description: "permission for \"im.kill.all\""
    default: op
  im.kill.damages:
    description: "permission for \"im.kill.damages\""
    default: op
  im.group:
    description: "permission for im group commands"
    default: true
  im.group.admin:
    description: "admin permission for im group commands"
    default: op